# These are supported funding model platforms

github: [alex-papaioannou] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: AlexPapaioannou # Replace with a single Patreon username https://patreon.com/AlexPapaioannou?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
open_collective: alex-papaioannou25 # Replace with a single Open Collective username
ko_fi: alexpapaioannou # Replace with a single Ko-fi username
tidelift: alex-papaioannou # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: alex-papaioannou # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
